package com.adimessi30.elevatorsystem.components.concrete;

import com.adimessi30.elevatorsystem.components.abstractions.IdAutoGenerated;
import com.adimessi30.elevatorsystem.enums.Direction;
import com.adimessi30.elevatorsystem.entities.ElevatorRequest;
import lombok.Getter;
import lombok.Setter;

import javax.annotation.concurrent.ThreadSafe;

import static com.adimessi30.elevatorsystem.enums.Direction.DOWN;
import static com.adimessi30.elevatorsystem.enums.Direction.IDLE;
import static com.adimessi30.elevatorsystem.enums.Direction.UP;

@ThreadSafe
@Getter
public class Elevator extends IdAutoGenerated {
    private final int elevatorId;
    private int currentFloor = 0;
    @Setter
    private Direction currentDirection = IDLE;

    public Elevator() {
        super();
        this.elevatorId = getId();
    }

    protected void move(ElevatorRequest elevatorRequest) {
        int distance = elevatorRequest.floorNumber() - currentFloor;
        currentDirection = distance > 0 ? UP : distance == 0 ? IDLE : DOWN;
        currentFloor = elevatorRequest.floorNumber();
        displayInfo();
    }

    protected void stop() {
        currentDirection = IDLE;
        displayInfo();
    }

    protected void postConstruct() {
//        System.out.printf("%nNew elevator instance with id: %d was created......%n", elevatorId);
        displayInfo();
    }

    private void displayInfo() {
        System.out.println("\n[ElevatorId: " + elevatorId + "] " + (IDLE.equals(currentDirection) ? "Current Floor: " + currentFloor :
                "Going " + currentDirection + " to floor: " + currentFloor));
    }
}
