package com.adimessi30.elevatorsystem.components.concrete;

import com.adimessi30.elevatorsystem.components.abstractions.IdAutoGenerated;
import com.adimessi30.elevatorsystem.entities.ElevatorRequest;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

import static com.adimessi30.elevatorsystem.enums.Direction.DOWN;
import static com.adimessi30.elevatorsystem.enums.Direction.UP;

@RequiredArgsConstructor
public class Floor extends IdAutoGenerated {
    @Getter
    private final int floorNumber;
    @Getter
    private boolean isTopFloor;
    private final Button buttonUp;
    private final Button buttonDown;

    public Floor(Button buttonUp, Button buttonDown) {
        super();
        this.floorNumber = getId();
        this.buttonUp = buttonUp;
        this.buttonDown = buttonDown;
    }

    protected void setTopFloor() {
        isTopFloor = true;
    }

    public void goUp() {
        if (isTopFloor) {
            System.out.println("This is the top floor.......");
        } else {
            buttonUp.callForElevator(new ElevatorRequest(floorNumber, UP));
        }
    }

    public void goDown() {
        if (floorNumber == 0) {
            System.out.println("This is the bottom floor.....");
        } else {
            buttonDown.callForElevator(new ElevatorRequest(floorNumber, DOWN));
        }
    }

    public void getFloorInfo() {
        System.out.printf("%nButtonUp: %s | ButtonDown: %s%n", buttonUp, buttonDown);
    }

    protected void postConstruct() {
//        System.out.printf("%nNew floor instance with floorNumber: %d was created........%n", floorNumber);
    }
}
