package com.adimessi30.elevatorsystem.components.abstractions;

public abstract class HasBackgroundRunnable extends IdAutoGenerated {

    private volatile boolean shouldShutdown = false;

    protected void init() {
        Thread thread = new Thread(() -> {
            while (!shouldShutdown) {
                run();
            }
        });
        thread.setDaemon(true);
        thread.start();
    }

    protected abstract void run();

    public void shutdown() {
        shouldShutdown = true;
    }
}
