package com.adimessi30.elevatorsystem.components;

import com.adimessi30.elevatorsystem.components.abstractions.IdAutoGenerated;
import com.adimessi30.elevatorsystem.managers.RequestDispatcher;
import com.adimessi30.elevatorsystem.entities.ElevatorRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@RequiredArgsConstructor
public class Button extends IdAutoGenerated {

    private final RequestDispatcher dispatcher;

    protected void callForElevator(ElevatorRequest elevatorRequest) {
        dispatcher.dispatch(elevatorRequest);
    }

    protected void postConstruct() {
        log.debug("New externalButton with instance id: {} was created.......", getId());
    }
}
