package com.adimessi30.elevatorsystem.components;

import com.adimessi30.elevatorsystem.components.abstractions.IdAutoGenerated;
import com.adimessi30.elevatorsystem.enums.Direction;
import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

import static com.adimessi30.elevatorsystem.enums.Direction.IDLE;

@Slf4j
@Getter
@Setter
public class Elevator extends IdAutoGenerated {
    private final int elevatorId;
    private int currentFloor = 0;
    private Direction currentDirection = IDLE;

    public Elevator() {
        super();
        this.elevatorId = getId();
    }

    protected void postConstruct() {
        log.debug("New elevator instance with id: {} was created......", elevatorId);
    }
}
