package com.adimessi30.elevatorsystem.components;

import com.adimessi30.elevatorsystem.components.abstractions.IdAutoGenerated;
import com.adimessi30.elevatorsystem.entities.ElevatorRequest;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

import static com.adimessi30.elevatorsystem.enums.Direction.DOWN;
import static com.adimessi30.elevatorsystem.enums.Direction.UP;

@Slf4j
public class Floor extends IdAutoGenerated {
    @Getter
    private final int floorNumber;
    @Getter
    private boolean isTopFloor;
    private final Button buttonUp;
    private final Button buttonDown;

    public Floor(Button buttonUp, Button buttonDown) {
        super();
        this.floorNumber = getId();
        this.buttonUp = buttonUp;
        this.buttonDown = buttonDown;
    }

    public void setTopFloor() {
        isTopFloor = true;
    }

    public void goUp() {
        if (isTopFloor) {
            log.info("This is the top floor.......");
        } else {
            buttonUp.callForElevator(new ElevatorRequest(floorNumber, UP));
        }
    }

    public void goDown() {
        if (floorNumber == 0) {
            log.info("This is the bottom floor.....");
        } else {
            buttonDown.callForElevator(new ElevatorRequest(floorNumber, DOWN));
        }
    }

    protected void postConstruct() {
        log.debug("New floor instance with floorNumber: {} was created........", floorNumber);
    }
}
