package com.adimessi30.elevatorsystem.components;

import com.adimessi30.elevatorsystem.components.abstractions.IdAutoGenerated;
import com.adimessi30.elevatorsystem.entities.ElevatorRequest;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;

import static com.adimessi30.elevatorsystem.enums.Direction.DOWN;
import static com.adimessi30.elevatorsystem.enums.Direction.UP;
import static com.adimessi30.elevatorsystem.helpers.HookFactory.getHookForButtonCallback;

@Slf4j
public class Floor extends IdAutoGenerated {
    @Getter
    private final int floorNumber;
    private final FloorButton floorButtonUp;
    private final FloorButton floorButtonDown;

    public Floor(FloorButton floorButtonUp, FloorButton floorButtonDown) {
        super();
        this.floorNumber = getId();
        this.floorButtonUp = floorButtonUp;
        this.floorButtonDown = floorButtonDown;
    }

    public void goUp() {
        if (floorButtonUp.canPressButton())
            floorButtonUp.sendRequestToDispatcher(ElevatorRequest.builder()
                    .floorNumber(floorNumber)
                    .direction(UP)
                    .buttonCallback(getHookForButtonCallback(floorButtonUp))
                    .build()
            );
    }

    public void goDown() {
        if (floorButtonDown.canPressButton())
            floorButtonDown.sendRequestToDispatcher(ElevatorRequest.builder()
                    .floorNumber(floorNumber)
                    .direction(DOWN)
                    .buttonCallback(getHookForButtonCallback(floorButtonDown))
                    .build()
            );
    }

    protected void postConstruct() {
        log.debug("New floor instance with floorNumber: {} was created........", floorNumber);
    }

    public void disableUp() {
        floorButtonUp.setDisabled(true);
    }

    public void disableDown() {
        floorButtonDown.setDisabled(true);
    }
}
