package com.adimessi30.elevatorsystem.components;

import com.adimessi30.elevatorsystem.components.abstractions.IdAutoGenerated;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@Slf4j
@RequiredArgsConstructor
public class Floor extends IdAutoGenerated {
    @Getter
    private final int floorNumber;
    @Getter
    private boolean isTopFloor;
    private final Button buttonUp;
    private final Button buttonDown;

    public Floor(Button buttonUp, Button buttonDown) {
        super();
        this.floorNumber = getId();
        this.buttonUp = buttonUp;
        this.buttonDown = buttonDown;
    }

    public void setTopFloor() {
        isTopFloor = true;
    }

    protected void postConstruct() {
        log.debug("New floor instance with floorNumber: {} was created........", floorNumber);
    }
}
